### ISSUE TITLE
Weapon Augments Feedback and Suggestions

### ISSUE THREAD

**Issue by Berzerkinblaze** [BlockCrusader/tML-Mods#16]
It's been a while since I made that comment on Steam asking if there was a Discord to post my experiences with the Leveling and Weapon Augment mods, and you said it was fine to post in-depth suggestions as a Github issue. While my memory on said experiences are a bit faded since some time has passed, I'm finally feeling up to expressing what I can on the matter.

To start, I find it very enjoyable to be able to go against Terraria bosses and enemies in general without holding back. As such, I decided to juice up a decent bit of the enemies with the Simple NPC Customizer mod in addition to allowing the Leveling Mod to buff enemies as I progress through the game (default settings of 3x HP and 1.5x defense when Moon Lord is defeated), in addition to Fargo's buffing boss and boss minion HP by 20%. With these factors in play, I don't have to worry much about shredding enemies too fast, so I can enjoy fights to the fullest, even when I'm leveling and augmenting my weapons to become quite powerful. In addition, there are sometimes weapons I grow attached to and want to get more use out of (took Terra Blade to the postgame at level 98 with Ultimate+ Committed, Precision, Dire, and Hypercrit, mainly to beat the You boss with because it just seemed so fitting), or maybe they fit a certain theme or aesthetic I'm sticking to, and leveling/augmenting them allows me to take them to their limits to punch up.

With the context for how I like to play out of the way, I'd like to get to the main stuff now. Regarding the augments, I like that there are relatively basic ones that increase weapon size, speed, damage, and such, as well as more flashy ones like Collateral, which is probably my favorite because of how much flair it can add to a weapon like the Zenith. I noticed that there are a decent few augments that rely on the deaths of enemies to trigger, such as Battlelust, Frenzy, Heartsurge, Deathshroud, Deathecho, Reaping, and Ward. While they do have their place and circumstances for use, I never really found myself using the majority of them too often, as they mainly found use during events and hardly ever otherwise, as enemies found while roaming aren't really that numerous unless you make them so, and most bosses don't swarm you with minions. I found myself gravitating towards the same DPS-increasing augments like Might, Relentless, Dire, Hypercrit, Kingslayer, Momentum, and Committed, even when I'd prefer to be using flashy, yet practical augments like Collateral more often. Of the ones I named, I think I like Hypercrit and Committed the most, as Hypercrit makes crit builds more spicy and Committed rewards you for actively keeping the pressure on a single, powerful enemy like a boss. I think my point regarding the enemy kill augments VS something like Committed is that there aren't more options for interesting effects against enemies that don't go down easily, or for rewarding aggression.

There are some balancing concerns I have. As I've noticed most notably during a playthrough with my friend, the Unusual Overflow and likely Battlelust augments can allow you to deal so much damage with a burst weapon that it hits the integer limit(?) and resets to low/normal damage. If possible, there should be a limit to how much of a boost these augments can give to a weapon. There are also the augments that have percentage-based effects, such as Unusual Siphon, Lifeleech, and Execution. Because of how high the numbers can get, I highly recommend having flat limits on the amount of mana/HP Siphon and Lifeleech can restore if they aren't in place already, as 15% of like 3000 damage with Ultimate Lifeleech is still a huge heal for a player, especially given that said heal may happen rapidly without cooldown. As for Execution, 5% max HP for a boss or 10% for a very tanky enemy is generally quite huge, especially given the 1 second cooldown. I would personally approach this with a higher cooldown alongside greatly-lowered execution damage for bosses. 1% of a boss's max HP every 5 seconds on top of regular damage output sounds pretty significant to me, especially on superbosses. I would also reduce the true boss execution threshold to 5%, mainly so bosses can remain menaces at death's door longer. Lastly, I personally found the Supercharge augment very hard to use, as it takes quite a while to build up the stacks and getting hit removes a lot of them. I dunno though, maybe I was using it at a bad time, and it's actually pretty practical.

As for augment suggestions, I have a few at the moment.

- Roundslash (Epic+) - Critical hits have a 25% chance to create a large circular slash, damaging enemies in range for X% damage and ignoring 50% of enemy defense.
[Inspired by Collateral and Blast; would ideally have a crispy slice sound effect as well]

- Overloading (Epic+) - Attacks from Overloading weapons have a small [~0.1%] chance to cause enemies to explode, dealing X% of the attack's damage + 10% of the enemy's max HP (1/2% for bosses) in a large area, with the chance gradually increasing based on the enemy's max HP compared to the damage dealt. Has a 10 second cooldown between explosions from each enemy.
[Mainly inspired by Committed; would ideally have a crispy explosion sound effect and cool sprite, and maybe some screen shake]

- Dormant (Rare+) - Weapon damage starts at 50%, but gradually increases to X% as the weapon is used in combat, gradually decreasing when not in combat.
[Inspired by Committed and Supercharge]

- Razorwind (Rare+) - Attacks have a 25% chance to spawn a flying cutter [like a demon scythe without the particles] on hit, which homes in on enemies and deals X% of the attack's damage up to 3 times.
- Razorwind (Unusual) - Attacks have a 10% chance to spawn a super flying cutter on hit, which homes in on enemies very quickly with relatively low tracking and deals X% of the attack's damage up to 9 times.
[Inspired by Barrage]

- Countdown (Rare+) - Attacks from Countdown weapons initiate a 10 second countdown on struck enemies, and X% of damage dealt from Countdown weapons on affected enemies during that time is inflicted when the countdown ends.
[Inspired by... something; could probably do with a bell sound effect when the countdown ends.]

The last thing I would like to suggest is color customization for augments. I'd like to have my augment effects match the color of the weapon I'm using them on, so I can have Ultimate+ Collateral on a red weapon generate red particles and slashes, rather than purple.

To sum everything up, I really enjoy what the Leveling and Weapon Augment mods add to the game, and I'd like to see the Weapon Augments mod expanded upon to add more interesting and fun augments, as well as color customization.

**Comment by BlockCrusader** [comment]
Thanks for all the feedback, I'm glad you're enjoying the mod overall!
- I do see that there aren't alot of Augments specifically for playing aggressively. I suppose that was the 'niche' (That's not really niche) that Committed fills (Though most offense-oriented Augments are still beneficial to said 'niche'), but it still wouldn't hurt for there to be more options for that playstyle. That said, I wasn't really planning on adding any more Augments to the mod due to the process being tedious and because I consider the mod to be in a finished state, so I'm not really sure what to do about it in light of that context.
- I'm not sure why Unusal Overflow and Battlelust are dealing so much damage, they shouldn't be able to stack with themselves so the most they should be giving is +150% (If you somehow killed an enemy at 1 hp) and x2 dmg (Could change to +100% to nerf stacking potential with other augments), respectively.
- Lifestealing effects _should_ be respecting the internal lifesteal cooldown (The same system Spectre armor and Vampire Knives operate under to cap their lifesteal), though if you heal a massive amount of HP at once that can effectively bypass it. Either way a hardcap on the max mana/HP stolen at once is a good idea. I guess I didn't think about it at the moment since I design my mods around vanilla (Where it's very rare to deal upwards of 500+ dmg per hit by endgame).
- From a mathematical standpoint, _on average_ Execution alone would take roughly 380 seconds to kill a boss (~20 attempts to trigger the 5% proc of Execution, and 19 successful Executions to kill equates to ~380 attempts at 1 attempt per second). That equates to over 6 minutes, which is very long for a Terraria boss fight from my experience (And even if we're talking mods, I'm pretty sure Nameless Deity's reactive DR is built around a 4-minute fight, for instance). On paper this seems roughly balanced to me, but again this doesn't account for the player's primary DPS so I could see some potential for it to be too much. When I get around to changes, I'll get rid of the boss insta-kill threshold altogether (Insta-kill will never proc) and nerf the proc. chance from 5% to 4% (Ult+ would also drop from 7% to 6%).
- I've not gotten any real chances to experiment with Supercharge in my playthroughs so I don't have a feel for how well it works in practice. That said, I could see the stack stripping being a bit much, so that could be nerfed some to be more forgiving.
- These are neat Augment ideas, but unfortunately - as mentioned before - I didn't have plans for developing further content. I like most of these, though, so I'd still like to play around with implementing them in some way. I was thinking perhaps adapting them to be Unusual variants of existing Augments? For instance; Roundslash could be an Unusual for Collateral, and make the bonus strike hit in a wider, arcing motion. I'm also not really happy with Unleash's Unusual, so I'm honestly considering just reworking it to be more like Dormant.
- Customizing dust color sounds easy. I could implement that as a client-side configuration setting.

I'm in the middle of a big update for another of my mods, Arsenal, so I dunno when I'll get around to making tweaks to Augments based on your feedback. 
When I do, though, I'll close this Issue (if I remember to, that is) once I've completed the changes, so you'll have a way to know when I've implemented stuff. Cheers!

**Comment by Berzerkinblaze** [comment]
I can ask my friend about the specific setup she has for the weapon to deal so much damage, so the cause is more clear. Perhaps that specific weapon has a mechanic that increases its own damage as well.

In regards to Execution, I was basing my thoughts on the maximum possible proc frequency via something like the Chain Gun, since I feel it's best to account for the most extreme, yet still practical case.

About Roundslash, I'm now thinking critical strike activation wouldn't be best, as it would reduce/remove synergy with augments like Voidic, which greatly reduces critical chance if I remember correctly, and Minicrit, which operates off of non-critical hits.

One thing I forgot to mention is about Void Shards; would it be possible to have them only remove the last-added augment on a weapon? It was kinda painful to have Supercharged be one of the last Augments on my Terra Blade, only for me to not like it too much and have to wipe all of the other augments as well.

The last thing I'd like to ask about at the moment is about the colors. When you say client-side configuration, what exactly do you have in mind? I was thinking of customization on an individual weapon basis, so I could have one weapon's augment theme be red, while another one of the same type's is green. I'm also wondering if the customizations would be visible to others in multiplayer, since client-side refers to the user only as far as I remember.

**Comment by BlockCrusader** [comment]
- It's also possible that Unusual Battlelust and Overflow _are_ stacking with themselves, which would be unintended. When I get to it I'll do some tests as well.
- 1 attempt per second is the maximum proc frequency for Execution; there's a 1-second cooldown between attempts.
- I would like Void Shards to be able to remove a single Augment at a time, I just never decided on how the system should work. Perhaps some people want it to remove the first (oldest) Augment in the list so they can get rid of older Augments that have been outclassed. Meanwhile, other people may prefer your usecase; getting rid of the last (newest) Augment in the list in case they put something on and change their mind about it. Of course, the most ideal solution would be to allow the user to just choose what they want gone. I have gotten a little better at UI stuff, so I may consider overhauling Augment application/removal into a more intuitive and flexible UI.
- I was planning on making it so that you can set a color, and then that color replaces the color of all Augment-related dusts for you (Other players keep whatever they set). TBH this is basically the best I can do without having to add on more modded data to items, which isn't preferable since that has potential to be expensive memory-wise and ups the complexity of implementation quite a bit (I know how to do it, it'd just be more of a hassle; more than it's worth IMO).

**Comment by BlockCrusader** [comment]
Did some quick testing to confirm the issue; Unusual Battlelust doesn't stack with itself (But is still a multiplicative boost), but Overflow _does_. That would definitely explain integer overflow; just killing a few (~5) slimes with a Sniper Rifle got me to over 13K damage. Will definitely fix that when I get to updating the mod.

**Comment by Berzerkinblaze** [comment]
Ah, I finally understand what you mean in regards to Execution; I thought the 1 second cooldown applied on successes, rather than attempts 😅 

I understand in regards to the Void Shards and colors, and while the color situation is unfortunate, it's good to know that there's a better possibility of more precise Augment usage.

It's also good that you found the cause of the overflow (badum tss 🥁).

I'd like to expand upon the Overloading idea by proposing that its explosion be electricity-based, which differentiates it from Blast and ties into the idea of being overloaded. I also had the ideas of enemies that are in the process of overloading emitting sparks every now and then as a visual indicator of the buildup, as well as a chance for a few lightning bolts carrying some of the explosion's damage to shoot in random directions upon successfully overloading. Perhaps the latter idea would be too much in practice, but I think it'd be pretty cool to see.

**Comment by BlockCrusader** [comment]
Hey, just wanted to let you know that I've just released an update for Weapon Augments that includes changes based on your feedback and suggestions!

- Unusual Overflow issue where it recycled its own damage is fixed. Thanks again for reporting that
- Turns out I did have hardcaps for per-hit lifesteal, but I slightly lowered them anyways. I also added a hardcap for Unusual Siphon's manasteal
- Execution has been slightly nerfed, per the changes mentioned in one of my previous comments
- Supercharge's on-hit penalty is little more forgiving now
- I was able to make it so that Void Shards only remove one Augment at a time. Furthermore, you can choose whether to remove the newest or oldest Augment via. holding Shift.
- A new Unusual variant of Collateral was added, which is inspired by your Roundslash idea. I decided to actually stick with the on-crit proc, to distinguish it more from normal Collateral. Though it won't synergize as well with Augments like Voidic, it will synergize with ones like Dire, Precision, Hypercrit, etc.
- A new Unusual variant of Deathecho was added, which is inspired by your Overloading idea; the blast's damage scales with the enemy's max HP (Like how Overloading would) instead of the attack's damage. This of course has softcaps and hardcaps in place so the damage doesn't get too insane when you kill a tanky boss
- Unusual Unleash has been reworked based on your Dormant idea. I decided to have the damage range from -10% to +40% instead, though
- There is also a new Unusual variant of Kingslayer, which scales based on the enemy's max HP instead of whether or not it's a boss. Hopefully this appeals to your desire for more Augments that reward targeting bigger/tankier targets.
- There is now a config option for customizing the color of Augment dust. I was also able to make it effect most of the projectiles spawned by Augments! It is client-side though, so people won't be able to see eachother's colors.

I hope you enjoy!
