### ISSUE TITLE
Prestiging a weapon causes it's damage to reset.

### ISSUE THREAD

**Issue by Blapzapp** [BlockCrusader/tML-Mods#20]
So we discvered this specifically with the old ones army sentry staffs as well as with the stardust dragon summon and the Terraprisma. 

Damage is increased all the way to level 100, how ever as soon as it's prestiged, it's actual damage is reset to its base value, while it's tool tip info claims it's damage is higher and increasing post first prestige. We used the white ethereal rune for these as we were looking to have fun with it and discover this.

**Comment by Blapzapp** [comment]
i have spend the last hour and change testing and messing around with it and it seems primarily late game items are affected, both across modded and base game. I disabled all but calamity and the weapons listed above were still having this issue, tried with a fresh character even, with no luck. it seems the lower damage weapons are okay (bee gun, wasp gun for example) and level/prestige just fine.

However the ballista staff (not wand or cane) and the others that the tavern keeper sells are affected, especially when the math can get the ballista staff up to 10k damage, i suspect its cause of some odd damage cap possibly? if needed I can provide video showing the moment the staff was prestiged the damage dropped instantly to what its base damage was or any logs that are helpful if you cannot replicate the issue.

**Comment by BlockCrusader** [comment]
Just looked into this and can confirm. Summon weapons are a bit weird in that - due to the system they use for dynamically updating their base damage - they don't inherently work with the modifications to weapon damage this mod makes. 
To get them to work I basically have to rewrite the damage-increasing code in separate place just for minion/sentry projectiles. The issue here is that I forgot to update that code to accommodate for Prestige's damage boosts when I made the update that added Prestige.
Thanks for reporting this bug, you can expect an update patching this soon!
